In [1]:
import pandas as pd

In [2]:
d = {
    'name':'superman',
    'age':30
}

In [4]:
data = pd.DataFrame([1,2,3,4], columns=['DC HERO'])
data


DC HERO
0        1
1        2
2        3
3        4

In [5]:
data = pd.DataFrame(d.values(), columns=['DC HERO'])
data

DC HERO
0  superman
1        30

In [14]:
d2 = {
    'name':'Spiderman',
    'age':30
}
data['Marvel'] = d2.values()
data

DC HERO     Marvel
0  superman  Spiderman
1        30         30

In [15]:
import numpy as np

In [25]:
arr1 = np.random.randint(10, size= (3,3))

In [18]:
arr1

array([[0, 4, 8],
       [9, 8, 1],
       [3, 0, 3]])

In [19]:
arr2 = np.random.randint(10, size= (3,2))
arr2

array([[8, 4],
       [4, 1],
       [8, 9]])

In [23]:
arr1

array([[6, 3, 2],
       [3, 0, 2],
       [2, 0, 9]])

In [26]:
arr11 = np.array([[0, 4, 8],
       [9, 8, 1],
       [3, 0, 3]])

In [27]:
arr11

array([[0, 4, 8],
       [9, 8, 1],
       [3, 0, 3]])

In [28]:
arr22 = np.array([[8, 4],
       [4, 1],
       [8, 9]])

In [29]:
arr22

array([[8, 4],
       [4, 1],
       [8, 9]])

In [33]:
arr223 = arr22.T
arr223

array([[8, 4, 8],
       [4, 1, 9]])