In [1]:
import numpy as np


In [2]:
lst =[1,2,3,4,5]
a1 = np.array(lst)
a1

array([1, 2, 3, 4, 5])

In [4]:
%timeit sum([i for i in range(100000)])

6.63 ms ± 2.55 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [5]:
%timeit np.sum()

10.3 ms ± 237 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
a2 = np.random.randint(10, size=(4,4))
a2

array([[0, 8, 2, 5],
       [7, 6, 1, 8],
       [6, 9, 9, 1],
       [9, 5, 5, 3]])

In [7]:
np.diag(a2)

array([0, 6, 9, 3])

In [13]:
l1 = [1,2,3,4,5,6,7,8,9]
l2 = l1[2:6]
l2[2]=0
l1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
a3 = np.array([1,2,3,4,5,6,7,8,9])
a33 = a3[2:5]
a33[:]=0
a3

array([1, 2, 0, 0, 0, 6, 7, 8, 9])

In [18]:
a13 = np.array([1,2,3,4,5,6,7,8,9])
a133 = a13[2:5].copy()
a133[:]=0
a13

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
a12 = np.array([9,8,7,4,5,6,3,2,1])
a12 > 4
a12[a12>4]

array([9, 8, 7, 5, 6])

In [22]:
for i in a12:
    if 2 == i:
        print(i)
        break

2


In [33]:
np.random.seed(0)
ar = np.array([2,4,5,7,8])
ar
np.searchsorted(ar,3,side= 'right')

1